# Generated by Django 5.1.3 on 2024-11-26 22:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "Employee", "verbose_name_plural": "Employees"},
        ),
        migrations.AlterField(
            model_name="employee",
            name="annual_leave_days",
            field=models.FloatField(default=15.0, verbose_name="Annual Leave Days"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Hire Date"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_manager",
            field=models.BooleanField(default=False, verbose_name="Is Manager"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Position"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="remaining_leave_days",
            field=models.FloatField(default=15.0, verbose_name="Remaining Leave Days"),
        ),
    ]
