# Generated by Django 5.1.3 on 2024-11-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendancerecord",
            options={"ordering": ["date"]},
        ),
    ]
