# Generated by Django 5.1.3 on 2024-11-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0002_remove_leaverequest_requested_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
